### ISSUE TITLE
Remove section in Readme?

### ISSUE THREAD

**Issue by Etamuk** [chr314/nautilus-copy-path#16]
Hello, 

no issue, just a information.
I just noticed randomly on gnome-look.org a new version of nautilus-copy-path. So I updated my last german translation with the two new lines. 
After installing this extension again (and after nautilus -q) I didn´t get the new translation shown. 
So I tried to reinstall by removing the extension. After that the new translation is shown in menu. Before that there was only an empty line in menu.
Maybe you can add a short info to users who are updating this extension and didn´t know that they have to uninstall before.
Or maybe a ## Remove section in Readme?

Kind regards

**Comment by chr314** [comment]
Hello
thanks for the report
I fixed the bug in the Makefile and added uninstall instructions in the readme
