### ISSUE TITLE
Feature request: Middle Mouse Paste

### ISSUE THREAD

**Issue by manticore-projects** [chr314/nautilus-copy-path#17]
Chr314,

thank you a lot for providing this extension and the Arch/Aur package. I love it and it works great.
One jumble request though: I am very used to pasting by using the Middle Mouse key (Button 3). Of course this does not work yet, because we are not selecting text in a widget. (Only) Ctrl-Insert works for pasting, but this is not easily accessible in the (most) terminals.

Would it be possible to add support for Inserting by Middle Mouse Button 3 please?
Thank you already, I tip my hat.

**Comment by manticore-projects** [comment]
https://wiki.archlinux.org/index.php/clipboard explains the back ground and offers some tools.

**Comment by chr314** [comment]
hello
just added check it out :smiley:

**Comment by manticore-projects** [comment]
Thank you a lot, awesome work!
Best regards

Andreas
