### ISSUE TITLE
Bug: Doesn't work in `recent` "folder"

### ISSUE THREAD

**Issue by mal-tee** [chr314/nautilus-copy-path#37]
Great extension! 

But it seems like "Copy Path" and "Copy Name" don't work inside the "recent" folder.

**Comment by chr314** [comment]
fixed in e1888b360547eaec0746fa954baf15ba3e1f4dfb

thank you

**Comment by mal-tee** [comment]
Thank you! I'll test it when it reaches the AUR. :)
