### ISSUE TITLE
[Feature request] Add "Copy basename"

### ISSUE THREAD

**Issue by benintech** [chr314/nautilus-copy-path#38]
Sometimes it's useful to copy just the basename, without extension

**Comment by chr314** [comment]
I'm not sure what you mean, can you give me an example?

**Comment by benintech** [comment]
Copy the filename, without extension.
Copy "test" for a file named "test.txt"

**Comment by chr314** [comment]
just added the option `name_ignore_extension` in the config.json file you can set it to `true`

**Comment by benintech** [comment]
Great, thanks !
