### ISSUE TITLE
Installation issue Ubuntu 20.04

### ISSUE THREAD

**Issue by Lemez** [chr314/nautilus-copy-path#44]
Sounds like just what I need, unfortunately I can't get it to work, Linux noob here, thanks

> 
> $ make install
> mkdir -p ~/.local/share/nautilus-python/extensions/nautilus-copy-path
> cp nautilus-copy-path.py ~/.local/share/nautilus-python/extensions
> cp nautilus_copy_path.py translation.py config.json ~/.local/share/nautilus-python/extensions/nautilus-copy-path
> cp -rf translations ~/.local/share/nautilus-python/extensions/nautilus-copy-path
> Restarting nautilus
> Traceback (most recent call last):
>   File "/home/jonathan/.local/share/nautilus-python/extensions/nautilus-copy-path.py", line 4, in <module>
>     from nautilus_copy_path import NautilusCopyPath
>   File "/home/jonathan/.local/share/nautilus-python/extensions/nautilus-copy-path/nautilus_copy_path.py", line 9, in <module>
>     require_version('Gtk', '4.0')
>   File "/usr/lib/python3/dist-packages/gi/__init__.py", line 117, in require_version
>     raise ValueError('Namespace %s is already loaded with version %s' %
> ValueError: Namespace Gtk is already loaded with version 3.0
> Initializing nautilus-dropbox 2020.03.04
> 
>

**Comment by chr314** [comment]
Hello @Lemez
i think the issue is that the ubuntu 20.04 is using gtk 3 nautilus
you can install older version of the extensions like 1.8.0
https://github.com/chr314/nautilus-copy-path/releases/tag/1.8.0

```bash
wget https://github.com/chr314/nautilus-copy-path/archive/refs/tags/1.8.0.zip

unzip 1.8.0.zip

cd nautilus-copy-path-1.8.0

make install
```

**Comment by ayang** [comment]
I am using ubuntu 22.04, same problem.
ValueError: Namespace Gtk is already loaded with version 3.0

**Comment by chr314** [comment]
@ayang  did you try the 1.8.0 ?
