### ISSUE TITLE
Gnome/Nautilus 44

### ISSUE THREAD

**Issue by abraham-sah** [chr314/nautilus-copy-path#47]
Is it compatible with Gnome/Nautilus 44?

**Comment by chr314** [comment]
i haven't tested it, but i don't think there are big changes that would broke the extension
if you tested it with 44 let me know

**Comment by abraham-sah** [comment]
Sure, I will.

**Comment by fewaltix** [comment]
Tested under OpenSuse Tumbleweed with Gnome 44, works flawlessly!

**Comment by chr314** [comment]
thanks @fewaltix
