### ISSUE TITLE
GTK4 issue on Ubuntu 22.04?

### ISSUE THREAD

**Issue by mlgoodson** [chr314/nautilus-copy-path#48]
I have two systems running Ubuntu 22.04 LTS. One works fine (but may have had copy path installed before the upgrade.  The other I have had issues with for some time, including after a fresh 22.04 install. Here is the traceback when it loads after it relaunches nautilus

Restarting nautilus
Traceback (most recent call last):
  File "/home/michael/.local/share/nautilus-python/extensions/nautilus-copy-path.py", line 4, in <module>
    from nautilus_copy_path import NautilusCopyPath
  File "/home/michael/.local/share/nautilus-python/extensions/nautilus-copy-path/nautilus_copy_path.py", line 9, in <module>
    require_version('Gtk', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Gtk is already loaded with version 3.0

Yes. I have Gtk 4. I have no idea why python is using Gtk3.  Not sure if anyone else is having this issue, but I thought I would pass it on. Love the extension on the system that it works on BtW.

Best,
Michael

**Comment by mlv-** [comment]
Same issue on the same system.

**Comment by iGhoneim** [comment]
Same issue on Fedora release 38 x86_64

**Comment by chr314** [comment]
what `pip show PyGObject`  and `sudo apt show python3-gi` returns?

**Comment by mlgoodson** [comment]
_pip show PyGObject_

```
Name: PyGObject
Version: 3.42.1
Summary: Python bindings for GObject Introspection
Home-page: https://pygobject.readthedocs.io
Author: James Henstridge
Author-email: james@daa.com.au
License: GNU LGPL
Location: /usr/lib/python3/dist-packages
Requires: pycairo
Required-by: 
```
_sudo apt show -a python3-gi_ 

```
Package: python3-gi
Version: 3.42.1-0ubuntu1
Priority: important
Section: python
Source: pygobject
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 765 kB
Depends: gir1.2-glib-2.0 (>= 1.48.0), python3 (<< 3.11), python3 (>= 3.10~), python3:any, libc6 (>= 2.14), libffi8 (>= 3.4), libgirepository-1.0-1 (>= 1.62.0-4~), libgirepository-1.0-1-with-libffi8 (>= 1.62.0-4~), libglib2.0-0 (>= 2.56.0)
Homepage: https://wiki.gnome.org/Projects/PyGObject
Task: minimal, server-minimal
Download-Size: 229 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
Description: Python 3 bindings for gobject-introspection libraries
 GObject is an abstraction layer that allows programming with an object
 paradigm that is compatible with many languages. It is a part of Glib,
 the core library used to build GTK+ and GNOME.
 .
 This package contains the Python 3 binding generator for libraries that
 support gobject-introspection, i. e. which ship a gir1.2-<name>-<version>
 package. With these packages, the libraries can be used from Python 3.

Package: python3-gi
Version: 3.42.0-3build1
Priority: important
Section: python
Source: pygobject
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 764 kB
Depends: gir1.2-glib-2.0 (>= 1.48.0), python3 (<< 3.11), python3 (>= 3.10~), python3:any, libc6 (>= 2.14), libffi8 (>= 3.4), libgirepository-1.0-1 (>= 1.62.0-4~), libgirepository-1.0-1-with-libffi8 (>= 1.62.0-4~), libglib2.0-0 (>= 2.56.0)
Homepage: https://wiki.gnome.org/Projects/PyGObject
Task: minimal, server-minimal
Download-Size: 229 kB
APT-Sources: http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
Description: Python 3 bindings for gobject-introspection libraries
 GObject is an abstraction layer that allows programming with an object
 paradigm that is compatible with many languages. It is a part of Glib,
 the core library used to build GTK+ and GNOME.
 .
 This package contains the Python 3 binding generator for libraries that
 support gobject-introspection, i. e. which ship a gir1.2-<name>-<version>
 package. With these packages, the libraries can be used from Python 3.

```

without the show -a argument, it only shows the first entry in python3-gi and shows a notification that there is one that isn't shown.

Thanks for looking into this.

**Comment by chr314** [comment]
thanks @mlgoodson 
i will checkout ubuntu in a vm when i will find some free time

**Comment by nicorellius** [comment]
Similar here. I installed Ubuntu 22.04 on a new laptop recently and when I went to use nautilus-copy-path, I can't get it to work. My other older laptop is running the same OS and nautilus-copy-path works great. I love this little app.

**Comment by chr314** [comment]
just tested it in ubuntu 22.04, it looks like they use older version of nautilus with gtk3
you can use the 1.8.0 version of the extension, it works
