### ISSUE TITLE
net-installer extracts files into wrong place

### ISSUE THREAD

**Issue by YanceyChiew** [chr314/nautilus-copy-path#49]
There is such a line of guide in the readme:

## [Net Install](https://github.com/chr314/nautilus-copy-path/blob/c05ae89cabbfc15594494dcb4da81b98a91a3640/README.md?plain=1#L12-L15C1)
```bash
curl -L https://raw.githubusercontent.com/chr314/nautilus-copy-path/master/net-installer.sh | sudo bash
```
This will cause the entire script to run as an elevated user, which is necessary for the `install_dependencies` function in `net-installer.sh`, but it also causes the path written in the [`install`](https://github.com/chr314/nautilus-copy-path/blob/c05ae89cabbfc15594494dcb4da81b98a91a3640/net-installer.sh#L12C1-L18) function to be based on the home directory of the root user.

```bash
...
install () {
  mkdir -p ~/.local/share/nautilus-python/extensions/nautilus-copy-path
  cp nautilus-copy-path.py ~/.local/share/nautilus-python/extensions
  cp nautilus_copy_path.py translation.py config.json ~/.local/share/nautilus-python/extensions/nautilus-copy-path
  cp -rf translations ~/.local/share/nautilus-python/extensions/nautilus-copy-path
  "${NAUTILUS_PATH}" -q || true
}
...
```
There are three ways to alleviate this problem:
- Install this extension into a path accessible to all users: `/usr/share/nautilus-python/extensions` .
- Add `-E` _`(--preserve-env)`_ flag between `sudo` and `bash`, which will preserve the user's environment variables.
- Put `sudo` in front of commands that do require root privileges to execute, instead of running the whole script in an elevated bash.

**Comment by chr314** [comment]
fixed
