### ISSUE TITLE
[Question] Is project abandoned?

### ISSUE THREAD

**Issue by Rirusha** [chr314/nautilus-copy-path#54]

**Comment by johnpiers** [comment]
I was wondering the same. I see in the Archlinux AUR, the last time the package was updated was 2023-01-31 03:05 (UTC). I also see that so far, no one has marked the package as "flag package out-of-date". That's generally a good sign?

The Arch AUR maintainer is  a fella who goes by the nomenclature "lukaszmoroz"

**Comment by chr314** [comment]
Not really abandoned. I've just been short on time lately, and it hasn't required any immediate fixes

@Rirusha feel free to contribute #53 its good idea

there also this #26 bug if anyone is interested

@johnpiers the aur is not out of date

**Comment by johnpiers** [comment]
Thank for the reply chr314. :-) Appreciate it. 

> @johnpiers the aur is not out of date

 Yeah, that's what I said:  **no one** has marked the package as "flag package out-of-date.  So by that I'm sure one will infer that the package is 'not' out of date.
