### ISSUE TITLE
Double entries on pop up menu

### ISSUE THREAD

**Issue by FatFace68** [chr314/nautilus-copy-path#56]
As the title says, double entries on menu. How do I change this please?
![Screenshot From 2024-12-31 10-57-18](https://github.com/user-attachments/assets/2ee2d351-1e4a-4168-84e0-056c142f8f3a)

**Comment by chr314** [comment]
Hi
- check if its installed multiple times, check these directories ~/.local/share/nautilus-python/extensions , /usr/share/nautilus-python/extensions
- try to reinstall
after any modification restart the nautilus with the command `nautilus -q` then run `nautilus` and check the output

**Comment by FatFace68** [comment]
Thank you. For some reason I had it installed twice. All good now. 

Cheers.
